/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.dadu;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JOptionPane;
import javax.swing.BorderFactory;
import javax.swing.JButton;

/**
 *
 * @author falmesino
 */

public class PermainanDadu2 extends javax.swing.JFrame {
    private final Pemain pemain;
    private final DaduObject dadu;
    private final HistoriPermainan historiPermainan;

    /**
     * Creates new form PermainanDadu2
     */
    public PermainanDadu2() {
        initComponents();
        
        // Bikin jadi ke tengah
        setLocationRelativeTo(null);
        
        this.pemain = new Pemain(1000_000);
        this.dadu = new DaduObject();
        this.historiPermainan = new HistoriPermainan(jTable1);
        
        // Perbarui saldo
        pemain.updateSaldo(LabelSaldo);
        
        // Tampilan
        
//        getContentPane().setBackground(new Color(20, 30, 50));
//        
//        jPanel1.setBackground(new Color(20, 30, 50));
//        jPanel2.setBackground(new Color(20, 30, 50));
//        jPanel3.setBackground(new Color(20, 30, 50));
//        
//        PanelDadu.setBackground(new Color(20, 30, 50));
//        PanelDaduJudul.setBackground(new Color(20, 30, 50));
//        PanelDaduJudul1.setBackground(new Color(20, 30, 50));
//        PanelJudul.setBackground(new Color(20, 30, 50));
//        PanelJudulGroup.setBackground(new Color(20, 30, 50));
//        PanelTombol.setBackground(new Color(20, 30, 50));
//        
//        styleButton(ButtonReset);
//        styleButton(ButtonDaduBesar);
//        styleButton(ButtonDaduKecil);
//        styleButton(ButtonTentang);
//        styleButton(ButtonWithdrawal);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelJudulGroup = new javax.swing.JPanel();
        PanelJudul = new javax.swing.JPanel();
        LabelJudul = new javax.swing.JLabel();
        LabelDeskripsi = new javax.swing.JLabel();
        ButtonTentang = new javax.swing.JButton();
        PanelDaduJudul1 = new javax.swing.JPanel();
        LabelSaldo = new javax.swing.JLabel();
        ButtonWithdrawal = new javax.swing.JButton();
        PanelDaduJudul = new javax.swing.JPanel();
        LabelJudulDadu1 = new javax.swing.JLabel();
        LabelJudulDadu2 = new javax.swing.JLabel();
        PanelDadu = new javax.swing.JPanel();
        LabelDadu1 = new javax.swing.JLabel();
        LabelPanelDaduSpacer = new javax.swing.JLabel();
        LabelDadu2 = new javax.swing.JLabel();
        PanelTombol = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        ButtonDaduBesar = new javax.swing.JButton();
        ButtonDaduKecil = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        ButtonReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dadu Gacor OOP - Kelompok 2");
        setMaximumSize(new java.awt.Dimension(640, 640));
        setMinimumSize(new java.awt.Dimension(640, 640));
        setPreferredSize(new java.awt.Dimension(640, 640));
        setResizable(false);
        setSize(new java.awt.Dimension(640, 640));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        PanelJudulGroup.setMaximumSize(new java.awt.Dimension(560, 80));
        PanelJudulGroup.setMinimumSize(new java.awt.Dimension(560, 80));
        PanelJudulGroup.setOpaque(false);
        PanelJudulGroup.setPreferredSize(new java.awt.Dimension(560, 80));
        PanelJudulGroup.setLayout(new javax.swing.BoxLayout(PanelJudulGroup, javax.swing.BoxLayout.LINE_AXIS));

        PanelJudul.setPreferredSize(new java.awt.Dimension(640, 80));
        PanelJudul.setLayout(new javax.swing.BoxLayout(PanelJudul, javax.swing.BoxLayout.Y_AXIS));

        LabelJudul.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        LabelJudul.setText("DADU GACOR OOP");
        PanelJudul.add(LabelJudul);

        LabelDeskripsi.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        LabelDeskripsi.setText("Tugas Akhir Mata Kuliah Pemrograman Berbasis Objek Kelompok 2");
        PanelJudul.add(LabelDeskripsi);

        PanelJudulGroup.add(PanelJudul);

        ButtonTentang.setText("Tentang");
        ButtonTentang.setMaximumSize(new java.awt.Dimension(100, 40));
        ButtonTentang.setMinimumSize(new java.awt.Dimension(100, 40));
        ButtonTentang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonTentangActionPerformed(evt);
            }
        });
        PanelJudulGroup.add(ButtonTentang);

        getContentPane().add(PanelJudulGroup);

        PanelDaduJudul1.setMaximumSize(new java.awt.Dimension(560, 40));
        PanelDaduJudul1.setMinimumSize(new java.awt.Dimension(560, 40));
        PanelDaduJudul1.setPreferredSize(new java.awt.Dimension(560, 40));
        PanelDaduJudul1.setLayout(new javax.swing.BoxLayout(PanelDaduJudul1, javax.swing.BoxLayout.LINE_AXIS));

        LabelSaldo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        LabelSaldo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LabelSaldo.setText("Saldo: 0");
        LabelSaldo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LabelSaldo.setMaximumSize(new java.awt.Dimension(280, 100));
        LabelSaldo.setMinimumSize(new java.awt.Dimension(280, 100));
        LabelSaldo.setPreferredSize(new java.awt.Dimension(280, 100));
        PanelDaduJudul1.add(LabelSaldo);

        ButtonWithdrawal.setText("Withdraw ke akun DANA");
        ButtonWithdrawal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonWithdrawal.setIconTextGap(0);
        ButtonWithdrawal.setMargin(new java.awt.Insets(0, 0, 0, 0));
        ButtonWithdrawal.setMaximumSize(new java.awt.Dimension(280, 100));
        ButtonWithdrawal.setMinimumSize(new java.awt.Dimension(280, 100));
        ButtonWithdrawal.setPreferredSize(new java.awt.Dimension(280, 29));
        ButtonWithdrawal.setSize(new java.awt.Dimension(280, 100));
        ButtonWithdrawal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonWithdrawalActionPerformed(evt);
            }
        });
        PanelDaduJudul1.add(ButtonWithdrawal);

        getContentPane().add(PanelDaduJudul1);

        PanelDaduJudul.setMaximumSize(new java.awt.Dimension(560, 40));
        PanelDaduJudul.setMinimumSize(new java.awt.Dimension(560, 40));
        PanelDaduJudul.setPreferredSize(new java.awt.Dimension(560, 40));
        PanelDaduJudul.setLayout(new javax.swing.BoxLayout(PanelDaduJudul, javax.swing.BoxLayout.LINE_AXIS));

        LabelJudulDadu1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        LabelJudulDadu1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelJudulDadu1.setText("Dadu 1");
        LabelJudulDadu1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LabelJudulDadu1.setMaximumSize(new java.awt.Dimension(280, 100));
        LabelJudulDadu1.setMinimumSize(new java.awt.Dimension(280, 100));
        LabelJudulDadu1.setPreferredSize(new java.awt.Dimension(280, 100));
        PanelDaduJudul.add(LabelJudulDadu1);

        LabelJudulDadu2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        LabelJudulDadu2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelJudulDadu2.setText("Dadu 2");
        LabelJudulDadu2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LabelJudulDadu2.setMaximumSize(new java.awt.Dimension(280, 100));
        LabelJudulDadu2.setMinimumSize(new java.awt.Dimension(280, 100));
        LabelJudulDadu2.setPreferredSize(new java.awt.Dimension(280, 100));
        PanelDaduJudul.add(LabelJudulDadu2);

        getContentPane().add(PanelDaduJudul);

        PanelDadu.setLayout(new javax.swing.BoxLayout(PanelDadu, javax.swing.BoxLayout.X_AXIS));

        LabelDadu1.setBackground(new java.awt.Color(255, 255, 255));
        LabelDadu1.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        LabelDadu1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelDadu1.setText("1");
        LabelDadu1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        LabelDadu1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LabelDadu1.setMaximumSize(new java.awt.Dimension(275, 100));
        LabelDadu1.setMinimumSize(new java.awt.Dimension(275, 100));
        LabelDadu1.setOpaque(true);
        LabelDadu1.setPreferredSize(new java.awt.Dimension(275, 100));
        PanelDadu.add(LabelDadu1);

        LabelPanelDaduSpacer.setMaximumSize(new java.awt.Dimension(10, 10));
        LabelPanelDaduSpacer.setMinimumSize(new java.awt.Dimension(10, 10));
        LabelPanelDaduSpacer.setPreferredSize(new java.awt.Dimension(10, 10));
        PanelDadu.add(LabelPanelDaduSpacer);

        LabelDadu2.setBackground(new java.awt.Color(255, 255, 255));
        LabelDadu2.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        LabelDadu2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelDadu2.setText("1");
        LabelDadu2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        LabelDadu2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LabelDadu2.setMaximumSize(new java.awt.Dimension(275, 100));
        LabelDadu2.setMinimumSize(new java.awt.Dimension(275, 100));
        LabelDadu2.setOpaque(true);
        LabelDadu2.setPreferredSize(new java.awt.Dimension(275, 100));
        PanelDadu.add(LabelDadu2);

        getContentPane().add(PanelDadu);

        PanelTombol.setMaximumSize(new java.awt.Dimension(560, 100));
        PanelTombol.setMinimumSize(new java.awt.Dimension(560, 70));
        PanelTombol.setPreferredSize(new java.awt.Dimension(560, 70));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tebak angka yang akan keluar");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setMaximumSize(new java.awt.Dimension(196, 30));
        jLabel1.setMinimumSize(new java.awt.Dimension(196, 30));
        jLabel1.setPreferredSize(new java.awt.Dimension(196, 30));
        PanelTombol.add(jLabel1);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        ButtonDaduBesar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        ButtonDaduBesar.setText("BESAR");
        ButtonDaduBesar.setMargin(new java.awt.Insets(0, 0, 0, 0));
        ButtonDaduBesar.setMaximumSize(new java.awt.Dimension(280, 40));
        ButtonDaduBesar.setMinimumSize(new java.awt.Dimension(280, 40));
        ButtonDaduBesar.setPreferredSize(new java.awt.Dimension(280, 40));
        ButtonDaduBesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDaduBesarActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonDaduBesar);

        ButtonDaduKecil.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        ButtonDaduKecil.setText("KECIL");
        ButtonDaduKecil.setMargin(new java.awt.Insets(0, 0, 0, 0));
        ButtonDaduKecil.setMaximumSize(new java.awt.Dimension(280, 40));
        ButtonDaduKecil.setMinimumSize(new java.awt.Dimension(280, 40));
        ButtonDaduKecil.setPreferredSize(new java.awt.Dimension(280, 40));
        ButtonDaduKecil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDaduKecilActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonDaduKecil);

        PanelTombol.add(jPanel1);

        getContentPane().add(PanelTombol);

        jPanel2.setMaximumSize(new java.awt.Dimension(560, 200));
        jPanel2.setMinimumSize(new java.awt.Dimension(560, 200));
        jPanel2.setPreferredSize(new java.awt.Dimension(560, 200));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tanggal", "Tebakan", "Hasil", "Menang", "Saldo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1);

        getContentPane().add(jPanel2);

        jPanel3.setMaximumSize(new java.awt.Dimension(560, 50));
        jPanel3.setMinimumSize(new java.awt.Dimension(560, 50));
        jPanel3.setPreferredSize(new java.awt.Dimension(560, 50));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("STOP JUDI ONLINE! OFFLINE SAJA!");
        jLabel2.setMaximumSize(new java.awt.Dimension(560, 16));
        jPanel3.add(jLabel2);

        ButtonReset.setText("Reset");
        ButtonReset.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonReset.setMargin(new java.awt.Insets(0, 0, 0, 0));
        ButtonReset.setMaximumSize(new java.awt.Dimension(93, 40));
        ButtonReset.setMinimumSize(new java.awt.Dimension(93, 40));
        ButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonResetActionPerformed(evt);
            }
        });
        jPanel3.add(ButtonReset);

        getContentPane().add(jPanel3);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonTentangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonTentangActionPerformed
        JOptionPane.showMessageDialog(
            this,
            "Tugas Akhir Mata Kuliah PBO\n"
                + "Kelompok 2\n"
                + "231232014 Muhamad Kosasih\n"
                + "231232022 Raihan Ramadhan\n"
                + "231232026 Muhammad Faisal Padhly\n"
                + "231232028 Falmesino Abdul Hamid\n"
        );
    }//GEN-LAST:event_ButtonTentangActionPerformed

    private void ButtonWithdrawalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonWithdrawalActionPerformed
        JOptionPane.showMessageDialog(this, "Fitur belum tersedia, jika pun tersedia kami pasti sudah kaya.");
    }//GEN-LAST:event_ButtonWithdrawalActionPerformed

    private void ButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonResetActionPerformed
        int konfirmasi = JOptionPane.showConfirmDialog(
            null,
            "Ulangi permainan? Saldo dan histori akan dikosongkan.",
            "Konfirmasi", // Title
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE
        );
        
        if (konfirmasi == JOptionPane.YES_OPTION) {
            pemain.setSaldo(1000_000);
            pemain.updateSaldo(LabelSaldo);
            historiPermainan.kosongkanHistoriPermainan();
            // model.setRowCount(0);
        } else if (konfirmasi == JOptionPane.NO_OPTION) {
            // ...
        } else if (konfirmasi == JOptionPane.CLOSED_OPTION) {
            // ...
        }
    }//GEN-LAST:event_ButtonResetActionPerformed

    private void ButtonDaduBesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDaduBesarActionPerformed
        // Jika masih punya saldo, lanjut
        if (pemain.masihPunyaSaldo()) {
            this.tebakDadu("besar");
        } else {
            JOptionPane.showMessageDialog(null, "Anda tidak memiliki saldo", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ButtonDaduBesarActionPerformed

    private void ButtonDaduKecilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDaduKecilActionPerformed
        // Jika masih punya saldo, lanjut
        if (pemain.masihPunyaSaldo()) {
            this.tebakDadu("kecil");
        } else {
            JOptionPane.showMessageDialog(null, "Anda tidak memiliki saldo", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ButtonDaduKecilActionPerformed
    
    // Logika gamenya ada di sini semua
    public void tebakDadu(String jenis) {
        // Tanya dulu mau pasang berapa
        String input = JOptionPane.showInputDialog(null, "Masukan taruhan:");
        
        // Kalau taruhannya tidak kosong, maka...
        if (input != null && !input.isEmpty()) {
            if (input.length() > 10) {
                // Validasi jika input taruhan terlalu banyak                
                JOptionPane.showMessageDialog(null, "Taruhan terlalu besar!.", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                try {
                    // Ubah nilai taruhan dari String menjadi integer
                    int taruhan = Integer.parseInt(input);

                    // Validasi nilai taruhan tidak boleh nol atau negatif
                    if (taruhan <= 0) {
                        JOptionPane.showMessageDialog(null, "Taruhan harus lebih dari 0.", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                    // Validasi jika saldo mencukupi
                    else if (taruhan > pemain.getSaldo()) {
                        JOptionPane.showMessageDialog(
                            null,
                            "Taruhan melebihi saldo Anda. Saldo Anda: " + CurrencyFormatter.formatAsRupiah(pemain.getSaldo()),
                            "Error",
                            JOptionPane.ERROR_MESSAGE
                       );
                    }
                    // Jika semua persyaratan oke, kocok dadunya
                    else {

                        /**
                         * kocokDadu() akan menghasilkan array/larik/deret
                         * dengan urutan sebagai berikut:
                         * 0 => angka dadu 1
                         * 1 => angka dadu 2
                         * 2 => total dari angka dadu 1 dan 2
                         */
                        int[] angkaDadu = dadu.kocokDadu();
                        int total = angkaDadu[2];

                        // Menentukan tebakan benar atau tidak
                        boolean menang = dadu.isMenang(jenis, total);

                        // Menampilkan angka pada dadu
                        LabelDadu1.setText(Integer.toString(angkaDadu[0]));
                        LabelDadu2.setText(Integer.toString(angkaDadu[1]));

                        // Pesan kemenangan
                        String pesan = "Tidak gacor, kang!";

                        if (menang) {
                            // Jika menang, tambah saldo sesuai taruhan
                            pemain.tambahSaldo(taruhan);

                            // Atur pesan
                            pesan = "Gacor, kang!";
                        } else {
                            // Jika kalah, kurangi saldo sesuai taruhan
                            pemain.kurangiSaldo(taruhan);
                        }

                        JOptionPane.showMessageDialog(
                            null,
                            pesan + " (" + total + ")",
                            "Informasi",
                            JOptionPane.INFORMATION_MESSAGE
                        );

                        // Perbarui teks saldo
                        pemain.updateSaldo(LabelSaldo);

                        // Histori Permainan
                        historiPermainan.tambahHistoriPermainan(jenis, total, menang, taruhan, pemain.getSaldo());
                    }
                } catch (NumberFormatException e) {
                    // Validasi jika nilai taruhan bukan angka
                    JOptionPane.showMessageDialog(null, "Taruhan harus berupa angka.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
            
        } else {
            // Jika inputan taruhan kosong
            JOptionPane.showMessageDialog(null, "Anda tidak memasukkan taruhan.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void styleButton(JButton button) {
        button.setFont(new Font("Arial", Font.BOLD, 16));
        button.setBackground(new Color(40, 60, 90));
        button.setForeground(Color.WHITE);
        button.setFocusPainted(false);
        button.setBorder(BorderFactory.createEmptyBorder(5, 15, 5, 15));
        button.setCursor(new Cursor(Cursor.HAND_CURSOR));

        // Add hover effect
        button.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                button.setBackground(new Color(80, 120, 180));
            }

            @Override
            public void mouseExited(MouseEvent e) {
                button.setBackground(new Color(40, 60, 90));
            }
        });
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PermainanDadu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PermainanDadu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PermainanDadu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PermainanDadu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PermainanDadu2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonDaduBesar;
    private javax.swing.JButton ButtonDaduKecil;
    private javax.swing.JButton ButtonReset;
    private javax.swing.JButton ButtonTentang;
    private javax.swing.JButton ButtonWithdrawal;
    private javax.swing.JLabel LabelDadu1;
    private javax.swing.JLabel LabelDadu2;
    private javax.swing.JLabel LabelDeskripsi;
    private javax.swing.JLabel LabelJudul;
    private javax.swing.JLabel LabelJudulDadu1;
    private javax.swing.JLabel LabelJudulDadu2;
    private javax.swing.JLabel LabelPanelDaduSpacer;
    private javax.swing.JLabel LabelSaldo;
    private javax.swing.JPanel PanelDadu;
    private javax.swing.JPanel PanelDaduJudul;
    private javax.swing.JPanel PanelDaduJudul1;
    private javax.swing.JPanel PanelJudul;
    private javax.swing.JPanel PanelJudulGroup;
    private javax.swing.JPanel PanelTombol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
